In [1]:
import pandas as pd

In [5]:
def my_function():
    pass

In [8]:
def my_sq(x):
    """Squarea a given value, x
    
    parameters
    ----------
    x: number
    
    returns
    -------
    a squared number
    """
    return x ** 2

In [7]:
my_sq(4)

16

In [9]:
my_sq?

Signature: my_sq(x)
Docstring:
Squarea a given value, x

parameters
----------
x: number

returns
-------
a squared number
File:      c:\users\danie\desktop\2018-10-python2\notebooks\<ipython-input-8-d369eadee932>
Type:      function


In [10]:
def avg_2(x, y):
    """calculates the average between 2 number
    """
    return (x + y) / 2

In [11]:
avg_2(10, 20)

15.0

In [12]:
assert avg_2(10, 20) == 15

In [14]:
df = pd.DataFrame({
    'a': [10, 20, 30],
    'b': [20, 30, 40]
})
df

a   b
0  10  20
1  20  30
2  30  40

In [15]:
(df['a'] + df['b']) / 2

0    15.0
1    25.0
2    35.0
dtype: float64

In [18]:
df['a'].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [19]:
def my_exp(x, e):
    """Raise x to the e power
    """
    return x ** e

In [21]:
df['a'].apply(my_exp, e=3)

0     1000
1     8000
2    27000
Name: a, dtype: int64

In [22]:
def print_me(x):
    print(x)

In [24]:
df

a   b
0  10  20
1  20  30
2  30  40

In [23]:
df.apply(print_me)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [29]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [27]:
df.apply(avg_3)

TypeError: ("avg_3() missing 2 required positional arguments: 'y' and 'z'", 'occurred at index a')

In [30]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [31]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [32]:
df.apply(avg_3_apply, axis=1)

IndexError: ('index out of bounds', 'occurred at index 0')

In [33]:
def avg_2_apply(row):
    x = row[0]
    y = row[1]
    return (x + y) / 2
df.apply(avg_2_apply, axis=1)

0    15.0
1    25.0
2    35.0
dtype: float64

In [34]:
import seaborn as sns

In [35]:
titanic = sns.load_dataset('titanic')

In [36]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [38]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
survived       891 non-null int64
pclass         891 non-null int64
sex            891 non-null object
age            714 non-null float64
sibsp          891 non-null int64
parch          891 non-null int64
fare           891 non-null float64
embarked       889 non-null object
class          891 non-null category
who            891 non-null object
adult_male     891 non-null bool
deck           203 non-null category
embark_town    889 non-null object
alive          891 non-null object
alone          891 non-null bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [39]:
import numpy as np

In [43]:
def count_missing(vec):
    null_vec = pd.isnull(vec)
    null_count = np.sum(null_vec)
    return null_count

In [44]:
titanic.apply(count_missing)

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [46]:
titanic['num_missing'] = titanic.apply(count_missing, axis=1)

In [47]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  num_missing  
0    man        True  NaN  Southampton    no  False            1  
1  woman       False    C    Cherbourg   yes  False            0  
2  woman       False  NaN  Southampton   yes   True            1  
3  woman       False    C  Southampton   yes  False            0  
4    man        True  NaN  Southampton    no   True            1

In [49]:
titanic.loc[titanic['num_missing'] > 1]

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
5           0       3    male   NaN      0      0   8.4583        Q   Third   
17          1       2    male   NaN      0      0  13.0000        S  Second   
19          1       3  female   NaN      0      0   7.2250        C   Third   
26          0       3    male   NaN      0      0   7.2250        C   Third   
28          1       3  female   NaN      0      0   7.8792        Q   Third   
29          0       3    male   NaN      0      0   7.8958        S   Third   
32          1       3  female   NaN      0      0   7.7500        Q   Third   
36          1       3    male   NaN      0      0   7.2292        C   Third   
42          0       3    male   NaN      0      0   7.8958        C   Third   
45          0       3    male   NaN      0      0   8.0500        S   Third   
46          0       3    male   NaN      1      0  15.5000        Q   Third   
47          1       3  female   NaN      0      0   7.7500        Q   Third   
48          0       3    male   NaN      2      0  21.6792        C   Third   
61          1       1  female  38.0      0      0  80.0000      NaN   First   
64          0       1    male   NaN      0      0  27.7208        C   First   
65          1       3    male   NaN      1      1  15.2458        C   Third   
76          0       3    male   NaN      0      0   7.8958        S   Third   
77          0       3    male   NaN      0      0   8.0500        S   Third   
82          1       3  female   NaN      0      0   7.7875        Q   Third   
87          0       3    male   NaN      0      0   8.0500        S   Third   
95          0       3    male   NaN      0      0   8.0500        S   Third   
101         0       3    male   NaN      0      0   7.8958        S   Third   
107         1       3    male   NaN      0      0   7.7750        S   Third   
109         1       3  female   NaN      1      0  24.1500        Q   Third   
121         0       3    male   NaN      0      0   8.0500        S   Third   
126         0       3    male   NaN      0      0   7.7500        Q   Third   
140         0       3  female   NaN      0      2  15.2458        C   Third   
154         0       3    male   NaN      0      0   7.3125        S   Third   
158         0       3    male   NaN      0      0   8.6625        S   Third   
159         0       3    male   NaN      8      2  69.5500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
680         0       3  female   NaN      0      0   8.1375        Q   Third   
692         1       3    male   NaN      0      0  56.4958        S   Third   
697         1       3  female   NaN      0      0   7.7333        Q   Third   
709         1       3    male   NaN      1      1  15.2458        C   Third   
718         0       3    male   NaN      0      0  15.5000        Q   Third   
727         1       3  female   NaN      0      0   7.7375        Q   Third   
732         0       2    male   NaN      0      0   0.0000        S  Second   
738         0       3    male   NaN      0      0   7.8958        S   Third   
739         0       3    male   NaN      0      0   7.8958        S   Third   
760         0       3    male   NaN      0      0  14.5000        S   Third   
766         0       1    male   NaN      0      0  39.6000        C   First   
768         0       3    male   NaN      1      0  24.1500        Q   Third   
773         0       3    male   NaN      0      0   7.2250        C   Third   
778         0       3    male   NaN      0      0   7.7375        Q   Third   
783         0       3    male   NaN      1      2  23.4500        S   Third   
790         0       3    male   NaN      0      0   7.7500        Q   Third   
792         0       3  female   NaN      8      2  69.5500        S   Third   
793         0       1    male   NaN      0      0  30.6958        C   First   
825         0       3    male   NaN      0      0   6.9

In [50]:
def avg_2(x, y):
    return (x + y) / 2

In [51]:
avg_2(df['a'], df['b'])

0    15.0
1    25.0
2    35.0
dtype: float64

In [52]:
def avg_2(x, y):
    if (x == 20):
        return np.NaN
    return (x + y) / 2

In [53]:
avg_2(df['a'], df['b'])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [54]:
avg_2(10, 20)

15.0

In [55]:
avg_2(20, 30)

nan

In [56]:
import numpy as np

In [58]:
avg_2_vec = np.vectorize(avg_2)

In [59]:
avg_2_vec(10, 20)

array(15.)

In [60]:
avg_2_vec(df['a'], df['b'])

array([15., nan, 35.])

In [61]:
df

a   b
0  10  20
1  20  30
2  30  40

In [66]:
def avg_2(x, y):
    if (x == 20):
        return np.NaN
    return (x + y) / 2

avg_2_vec = np.vectorize(avg_2)

In [67]:
@np.vectorize
def v_avg_2(x, y):
    if (x == 20):
        return np.NaN
    return (x + y) / 2

In [68]:
v_avg_2(df['a'], df['b'])

array([15., nan, 35.])

In [69]:
import numba

In [70]:
@numba.vectorize
def v_avg_2_numba(x, y):
    if (x == 20):
        return np.NaN
    return (x + y) / 2

In [72]:
v_avg_2_numba(df['a'].values, df['b'].values)

array([15., nan, 35.])

In [75]:
pwd

'C:\\Users\\Danie\\Desktop\\2018-10-python2\\notebooks'

In [76]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 5E6B-FE5B

 Directory of C:\Users\Danie\Desktop\2018-10-python2\notebooks

2018-10-25  14:35    <DIR>          .
2018-10-25  14:35    <DIR>          ..
2018-10-17  08:54                 0 .gitkeep
2018-10-25  13:51    <DIR>          .ipynb_checkpoints
2018-10-25  10:12           151,087 01-intro.ipynb
2018-10-18  10:27           224,824 01-intro_pandas.ipynb
2018-10-25  10:35            28,024 02-data_structures.ipynb
2018-10-25  11:18           209,169 03-plots.ipynb
2018-10-25  12:00            59,600 04-combine.ipynb
2018-10-25  13:30            12,588 05-loops.ipynb
2018-10-25  13:50           153,140 06-missing.ipynb
2018-10-25  14:35            94,802 07-apply.ipynb
               9 File(s)        933,234 bytes
               3 Dir(s)  36,382,564,352 bytes free


In [79]:
%%timeit
avg_2_vec(df['a'], df['b'])

69.9 µs ± 945 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [81]:
%%timeit
v_avg_2_numba(df['a'].values, df['b'].values)

9.23 µs ± 60.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
